### ISSUE TITLE
Location is left blank after parsing

### ISSUE THREAD

**Issue by danrlu** [nextstrain/ncov-ingest#179]
Thanks so much for such useful scripts!!!

**Current Behavior**  
In raw gisaid data:
`zstdgrep "Southern San Joaquin Valley" gisaid.ndjson.zst` gives
`{"covv_accession_id": "EPI_ISL_2171674", "covv_add_host_info": "", "covv_assembly_method": "iVar 1.2.2 / BWA 0.7.17-r1188", "covv_collection_date": "2021-01-24", "covv_comment": "", "covv_comment_type": "", "covv_host": "Human", "covv_location": "North America / USA / California / Southern San Joaquin Valley", ....`

After 
```
/ncov-ingest/bin/transform-gisaid     \
        gisaid.ndjson                     \ 
       --output-metadata metadata.tsv    \ 
       --output-fasta sequences.fasta    \ 
       --output-unix-newline`
```

The `metadata.tsv` would remove `Southern San Joaquin Valley` from `location` column:
![image](https://user-images.githubusercontent.com/20667188/121100072-aae85a80-c7be-11eb-835d-8e6f7c6ea14f.png)

**Expected behavior**  
All location information be carried over to the transformed metadata.tsv

**How to reproduce**  
Steps to reproduce the current behavior:  
Latest version of the repo.

Or am I missing some filtering the `ncov-ingest` does on metadata?

**Comment by joverlee521** [comment]
Hi @danrlu, this behavior is due to the [default location rules](https://github.com/nextstrain/ncov-ingest/blob/master/source-data/gisaid_geoLocationRules.tsv) that are applied. Within Nextstrain we have standardized USA locations to counties, so any location that is not at the county level is intentionally left blank. 

If you wish to keep specific locations within your own metadata, I recommend editing your local `gisaid_geoLocationRules.tsv` file or supply your own custom rules via the `--geo-location-rules` option.

**Comment by danrlu** [comment]
Great to know! Thank you very much!
