### ISSUE TITLE
Align Nextclade threads and daily CPUs

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#326]
From @ivan-aksamentov in review of #320: 

> one thing I noticed is that `threads` in Nextclade's workflow is hardcoded to `64`, while daily ingest runs on `16` it seems:
https://github.com/nextstrain/ncov-ingest/blob/f27c9c8de125906c3ce7d5f62067cb92790e2f8b/.github/workflows/fetch-and-ingest-gisaid-master.yml#L68
>
> Some oversubscription can make it a bit faster under certain conditions. But 4x oversubscription likely don't.
>
> We might need to align these two numbers somehow.

**Comment by corneliusroemer** [comment]
I'm not quite sure I understand this @ivan-aksamentov 

Are you saying 64 CPUs is too much for full runs, not making use of all the CPUs? Would be good to have some data here. I could test on an AWS machine with 64 CPUs vs 16 CPUs vs 128 CPUs...

For daily runs we deal with much much less data so we could even go lower than 16 CPUs, though I'm not sure why if it doesn't cost efficiency to use more CPUs.

**Comment by ivan-aksamentov** [comment]
@corneliusroemer I am saying that ncov-ingest Snakemake gives Nextclade `--jobs=64`, but then that Snakemake workflow runs on a machine with 16 threads. This is likely inefficient and slows things down. These numbers need to be roughly equal.

**Comment by corneliusroemer** [comment]
Thanks, that makes sense now!

**Comment by tsibley** [comment]
I think there's some confusion about how the `threads:` value of a Snakemake rule works. The `threads:` values are upper bounds and are limited by the actual `--cores` / `--jobs` / `-j` value given to Snakemake on each run. So while the ncov-ingest Snakefile does specify 64 threads for the `run_nextclade` rule:

https://github.com/nextstrain/ncov-ingest/blob/f13ab1c8ed71c2229fb8c2206febd94d4c9095b3/Snakefile#L206

In practice this number is clamped down to 16 because that's ultimately what's passed to the `snakemake` invocation.
