### ISSUE TITLE
Duplicate locations

### ISSUE THREAD

**Issue by danrlu** [nextstrain/ncov-ingest#332]
### Context
We're noticing samples from the same place? 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/20667188/181854090-a885cc5f-4e91-4038-9e76-8f3c095f4fa0.png">

<img width="937" alt="image" src="https://user-images.githubusercontent.com/20667188/181854332-d3a5d29f-e1e0-482d-bfac-173f03eeff34.png">

### Description
Add to the [gisaid_geoLocationRules.tsv](https://github.com/nextstrain/ncov-ingest/blob/master/source-data/gisaid_geoLocationRules.tsv)

Sorry to not open a PR. I don't have a system set up to test the change easily TnT

Thank you very much!

**Comment by emmahodcroft** [comment]
Hi @danrlu ! Thanks for flagging this. We actually aren't doing as much curation beyond 'division' level (here that would be 'Magdalena' as we used to, simply because of the effort it takes to sort out smaller locations & the lack of time. However, this was a pretty easy one so I've added it in a PR #333  here, which hopefully should be merged soon!

**Comment by danrlu** [comment]
Thanks very much Emma! This totally makes sense. We may continue to notice these (on the `location` level) in the future given the nature of our product. Would you guys want to have those future corrections integrated to this repo, or we should just keep a local copy of the location rules?

**Comment by emmahodcroft** [comment]
If you are able @danrlu, then making a PR would be really valuable to us! If you check out what I did in mine you can do something similar - edit the file so that it corrects the location (it's worth searching first to ensure that the location isn't in there already and gets a more complex name - as was the case here with us calling it `Santa Marta (Magdalena)` (since there are more than one)).
Then we can review, and merge in, and hopefully even more people can benefit! Even though it's not something we can dedicate time to doing directly anymore, we'd of course be happy to keep things updated for everyone if others like yourself are finding these!

**Comment by danrlu** [comment]
Sounds good and will do!! Thanks very much!
