### ISSUE TITLE
Unable to build Docker image

### ISSUE THREAD

**Issue by victorlin** [nextstrain/ncov-ingest#413]
I [ran](https://github.com/nextstrain/ncov-ingest/actions/runs/5720552207) update-image.yml on `master` and it failed while running `pipenv sync` in the Docker build.

```
ValueError: "Requirement" object has no field "use_pep517"
```

Others on the internet have [reported](https://stackoverflow.com/a/76724894) that this error comes from a version of PyYAML (which is included in the Pipfile.lock).

I tried re-generating the lock file using `pipenv lock` locally but it failed.

**Comment by tsibley** [comment]
I haven't dug, so this is a guess, but I'm guessing this issue is restricted to Pipenv and the same version of PyYAML would be fine with standard Pip. If so, that's all the more reason to ditch Pipenv, like we've done [elsewhere](https://github.com/nextstrain/cli/commit/19c1514718ae457d579905efab587b062780873a). If we need strict locking, we can use pip-compile from pip-tools, [as elsewhere](https://github.com/nextstrain/wiki-redirector/blob/9c414e1fd92aac7f0dcbfc4aac3746fd9aa0ecfc/Makefile).
