### ISSUE TITLE
Stop triggering rebuild on edits to annotations

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/ncov-ingest#76]
A rebuild is not needed every single time, and manual rebuilds are easy to re-trigger. This will result in about the same amount of effort (triggering 50% of the time vs. the status quo of cancelling 50% of the time), but is more logical and results in fewer Slack notifications. 

(See [this Slack thread](https://bedfordlab.slack.com/archives/CTZKJC7PZ/p1594147551229600) for the original context.)

**Comment by tsibley** [comment]
Might also be worth making annotation updates remake the metadata.tsv from the _existing_ gisaid.ndjson/genbank.ndjson instead of pulling down new data from GISAID/GenBank too.

**Comment by joverlee521** [comment]
So making separate github workflows for `push` and `repository_dispatch`?
I imagine we then give `ingest-gisaid` a `--rebuild` option?

**Comment by kairstenfay** [comment]
Proposed by @emmahodcroft:

> Perhaps we could have three things:
> * command to explicitly pull new data (and rebuild metadata)
> * command to rebuild metadata files (also auto triggered by updating annotations file) & re-run 'location hierarchy' alerts
> * command to start the build (which we have)

**Comment by emmahodcroft** [comment]
After discussion with @eharkins & @MoiraZuber ([here](https://bedfordlab.slack.com/archives/CTZKJC7PZ/p1594720923330800?thread_ts=1594690535.330100&cid=CTZKJC7PZ)) I think what we'd like is:

- New data is only looked for with an explicit command, to avoid 'accidentally' getting new sequences when just trying to correct 'existing' ones. However, pulling in new data automatically runs `ncov-ingest` (so we get a metadata files, new locs, etc). It does **not** start a build
- Pushing to `gisaid_annotations` or `location_hierarchy` re-runs `ncov-ingest` but without pulling new data in - only corrects 'existing' data. This can *also* be triggered manually. Again, it does **not** start a build.
- Finally, you then start a build by using the existing build command, so that one doesn't start until all is ready to go. A build does not start automatically.

Currently we have two commands, one to run `ncov-ingest` with pulling in new data & then run `ncov`, and one to just start `ncov`:
```
./bin/trigger ingest --user <user>
./bin/trigger rebuild --user <user>
```
So, we could keep the second command the same - it start 'running the build' (`ncov`)

The first command (`ingest`) could perhaps just run `ncov-ingest`, without ingesting new data. This should also happen if there are changes to `gisaid-annotations` or `location_hierarchy` - however it should *not* automatically start 'running a build' (`ncov`)

Finally we could then have a new command (perhaps `pull-data` or something), which looks for and pulls new data from GISAID, and then runs `ncov-ingest` (as the data's not really usable to us unless we make new metadata, etc files)

Would this be possible to implement, @tsibley @kairstenfay @joverlee521 ? Thanks for your patience with us figuring this out, and hope this seems doable-reasonable - but we definitely discuss further!

**Comment by joverlee521** [comment]
@emmahodcroft Totally do-able. As the first step, I've stopped the auto-builds on ingest (see commit https://github.com/nextstrain/ncov-ingest/commit/c527af04b9bf5e6c114bc329098edd2d177f1ca3)

**Comment by emmahodcroft** [comment]
If we could move this forward it would be a big advantage to the builds! So we don't get new sequences every time we try to update the annotations. I believe the PR seems pretty ready, any chance we could merge? (Happy to have some warning to ensure know all the new commands!)
