### ISSUE TITLE
Rewrite transform-gisaid to perform a streaming transform

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/ncov-ingest#77]
My system's out of memory killer is stopping my local run of `./bin/transform-gisaid`. Because we're using Pandas, we're loading all the GISAID data into memory. Consider rewriting the script to use a streaming transform instead.

**Comment by huddlej** [comment]
It looks like the data are in the correct format to enable pandas's chunking of the JSON as you read it in. For example:

```python
df = pd.read_json("gisaid.ndjson", lines=True, chunksize=1000)
for chunk_df in df:
    print(chunk_df.shape)

# Prints:
# (1000, 19)
# (1000, 19)
# ...
```

Since each chunk is a valid data frame, you may be able to add the chunking in the top-level of the script and keep all the downstream processing functions the same...

**Comment by tsibley** [comment]
One issue with either a chunking or streaming approach here is that the transformation includes both sorting and de-duplicating.

https://github.com/nextstrain/ncov-ingest/blob/2a7fd99f45c4c140d9223a21ba6f1a412fbefbd8/bin/transform-gisaid#L65-L73

It is possible to implement _some_ de-duplication schemes in a streaming/chunking fashion, but ours depends on a sort to choose the preferred record.

**Comment by huddlej** [comment]
What if the de-duplication is decoupled from the other transformations and happens as a first pass through the data? This could look like:

Pass 1: Find and resolve duplicate strains into a set of valid strains/epi ids without sorting (akin to single pass methods to find the max/min values in an array). This might be implemented with a dictionary to track the length and epi id by strain name, but it could be reduced to a set after the pass finishes.

Pass 2: Transform records with standardization function and output metadata and sequences for valid strains epi ids.

A single pass through the compressed JSON takes ~20 seconds and the set of strain/epi ids shouldn't consume much memory compared to the full JSON. Lookups into this set will also be fast for the second pass.

Alternately, this does seem headed in the direction where databases shine, but I get that's not where we want to spend time right now. :)

**Comment by tsibley** [comment]
I agree that sort of two-pass approach could work. There would be some normalization/computation that would have to be applied at the start of both passes, since it effects `strain` and `length`.

One downside of scanning through the input twice is that the file (a few hundred MBs) will have to be downloaded twice if the file is streamed directly from S3 (or we'd have to [add some caching](https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=cache#caching-files-locally)). The automation always uses an already-existing local file, though, so this would only effect dev from time to time and is thus probably fine.
